version: "3.0"
      
networks:
  proxy:
    #external: true
  internal:
    #external: false

services:
  db:
    image: tutum/mongodb
    container_name: mongo-container
    environment:
      - AUTH=no
    ports:
      - 27017:27017
      - 28017:28017
    networks:
      - internal
  historico:
    image: jjpera/estudo-spring-historico:0.2
    #build: ../estudo-spring-historico/spring-server-generated/.
    container_name: historico-container
    environment:
      - DB_DOMAIN=${DB_DOMAIN}
    ports:
      - 8081:8081
    working_dir: /tmp
    command: java -jar app.jar
    depends_on:
      - db
    networks:
      - internal
      - proxy
